/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppDeliveriesRouteImport } from './routes/_app/deliveries'
import { Route as AppOperatorRouteImport } from './routes/_app/operator'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppQualityRouteImport } from './routes/_app/quality'
import { Route as AppTrendsRouteImport } from './routes/_app/trends'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorRoute = AppOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/deliveries': typeof AppDeliveriesRoute
  '/operator': typeof AppOperatorRoute
  '/overview': typeof AppOverviewRoute
  '/pipeline': typeof AppPipelineRoute
  '/quality': typeof AppQualityRoute
  '/trends': typeof AppTrendsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/deliveries': typeof AppDeliveriesRoute
  '/operator': typeof AppOperatorRoute
  '/overview': typeof AppOverviewRoute
  '/pipeline': typeof AppPipelineRoute
  '/quality': typeof AppQualityRoute
  '/trends': typeof AppTrendsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/deliveries': typeof AppDeliveriesRoute
  '/_app/operator': typeof AppOperatorRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/trends': typeof AppTrendsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/deliveries'
    | '/operator'
    | '/overview'
    | '/pipeline'
    | '/quality'
    | '/trends'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/deliveries'
    | '/operator'
    | '/overview'
    | '/pipeline'
    | '/quality'
    | '/trends'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/deliveries'
    | '/_app/operator'
    | '/_app/overview'
    | '/_app/pipeline'
    | '/_app/quality'
    | '/_app/trends'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries': {
      id: '/_app/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operator': {
      id: '/_app/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AppOperatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDeliveriesRoute: typeof AppDeliveriesRoute
  AppOperatorRoute: typeof AppOperatorRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppQualityRoute: typeof AppQualityRoute
  AppTrendsRoute: typeof AppTrendsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDeliveriesRoute: AppDeliveriesRoute,
  AppOperatorRoute: AppOperatorRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppQualityRoute: AppQualityRoute,
  AppTrendsRoute: AppTrendsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
